### PR TITLE
Upgrade and modernize

### PR DESCRIPTION
**Pull request by julianbei**
```
➜ npm audit

                       === npm audit security report ===

# Run  npm install --save-dev mocha@6.2.2  to resolve 2 vulnerabilities
SEMVER WARNING: Recommended action is a potentially breaking change
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimatch                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ mocha [dev]                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ mocha > glob > minimatch                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/118                             │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Critical      │ Command Injection                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ growl                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ mocha [dev]                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ mocha > growl                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/146                             │
└───────────────┴──────────────────────────────────────────────────────────────┘


# Run  npm install js-yaml@3.13.1  to resolve 3 vulnerabilities
SEMVER WARNING: Recommended action is a potentially breaking change
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ underscore.string                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ js-yaml                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ js-yaml > argparse > underscore.string                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/745                             │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Denial of Service                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ js-yaml                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ js-yaml                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ js-yaml                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/788                             │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Code Injection                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ js-yaml                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ js-yaml                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ js-yaml                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/813                             │
└───────────────┴──────────────────────────────────────────────────────────────┘


found 5 vulnerabilities (2 moderate, 2 high, 1 critical) in 21 scanned packages
  5 vulnerabilities require semver-major dependency updates.
```

### CODE REVIEW

**Comment by julianbei** [comment]
Related:
https://github.com/snowplow-referer-parser/nodejs-referer-parser/issues/7

**Comment by julianbei** [comment]
@mkatrenik can you please have a look?

**Comment by MrJibus** [comment]
Hello,

Also intereted to use this library :) 

@mkatrenik , could you please check this pull request ?

**Comment by julianbei** [comment]
@chuwy can you help?

**Comment by mcadamm4** [comment]
@julianbei @chuwy Hey guys, using this library and would like to see this branch merged in and the security issues solved.

**Comment by greg-md** [comment]
2022 and still not resolved? :(

**Pull request closed without merging**
