### PR TITLE
Migrate to Typescript and add FP style API 

### PR DESCRIPTION
**Pull request by julianbei**
Add 
- [x] Rewrite in Typescript
- [x] Types
- [x] an additional and optional more FP friendly API under `referer-parser/fp`
- [x] Linting
- [x] convert snake_case to camelCase and PascalCase
- [x] Lazy loading of `referers.yml`

This includes breaking changes and is a major release

### CODE REVIEW

**Comment by julianbei** [comment]
So CI is missing in this project. can you sign up for a free OOS tier at circle ci?

**Comment by julianbei** [comment]
@chuwy can you have a look? the original maintainer did not respond to the other PR: #8 since December last year

**Comment by julianbei** [comment]
depends on #8

**Comment by paulboocock** [comment]
Hi @julianbei and @philicious 
I noticed a couple of more recent commits here, is there anything I can gelp with to move this along so we can look at getting a release out? The thing that appears to be missing at the moment is a Github Action to package and release it, plus a review of this code. I can look at scheduling in a review, and perhaps even building the release automation, if you're happy with where this is at now?

**Comment by philicious** [comment]
@julianbei I didnt notice you had a PR open here when I was fixing up our branch. you would need to rollback my changes or cherry-pick to a different branch, to make this PR good again

**Pull request closed without merging**
